receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

exporters:
    otlphttp:
      traces_endpoint: "https://ingest.us1.signalfx.com/v2/trace/otlp"
      headers:
          "X-SF-Token": "${SPLUNK_ACCESS_TOKEN}"
    signalfx:
      access_token: "${SPLUNK_ACCESS_TOKEN}"
      access_token_passthrough: true
      realm: us1
      timeout: 5s
      max_idle_conns: 80
      log_data_points: true
      exclude_metrics: []
    debug:
      verbosity: normal
processors:
    batch:
      timeout: 10s
      send_batch_size: 1024

extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679

service:
    telemetry:
      logs:
        level: info
    extensions: [pprof, zpages, health_check]
    pipelines:
       traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlphttp]
       metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [signalfx]
